_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.11
            "6": 4.52.4
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
communication_turns:
    value: 3
games_per_round:
    value: 10
model_name:
    value: nilq/mistral-1L-tiny
num_rounds:
    value: 10
temperature:
    value: 0.7
